# syntax=docker/dockerfile:1

ARG PYTHON_VERSION=3.10

FROM python:$alpine

ARG uid=1000
ARG gid=1000

RUN addgroup --gid $gid sphinx \
 && useradd --uid $uid --gid $gid -M sphinx

WORKDIR /src
COPY requirements.txt docs-requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt -r docs-requirements.txt
#switches the user context for subsequent docker commands. Any subsequent commands in the Dockerfile will be executed with the permissions and privileges of the "sphinx" user. "sphinx" is a non-root user for security purposes. 
USER sphinx
